---
title: François D'Agostini
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: francois.dagostini@gmail.com
description: "Let's talk about code \n"
baseurl: ''
url: ''
github_username: fdagosti
header_pages:
- writing/writing.html
- projects/projects.html
- resume/resume.html
markdown: kramdown
sass:
  load_paths:
  - _sass
name: François D'Agostini
contact_urls:
  linkedin:
    url: https://www.linkedin.com/in/fdagostini
    label: LinkedIn
    icon: linkedin-square
  github:
    url: https://github.com/fdagosti
    label: GitHub
    icon: github-square
  email:
    url: mailto:francois.dagostini@gmail.com
    label: Email
    value: francois.dagostini@gmail.com
    icon: envelope-square
