# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: François D'Agostini
email: francois.dagostini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's talk about code 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  fdagosti

header_pages:
  - writing/writing.html
  - projects/projects.html
  - resume/resume.html

# Build settings
markdown: kramdown

sass:
    load_paths:
        - _sass

# Bio
name: "François D'Agostini"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/fdagostini"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/fdagosti"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:francois.dagostini@gmail.com"
    label: "Email"
    value: "francois.dagostini@gmail.com"
    icon: "envelope-square"